# Generated by Django 4.1.6 on 2023-02-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
