# Generated by Django 4.1.6 on 2023-02-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
