# Generated by Django 4.1.6 on 2023-02-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
