# Generated by Django 4.1.6 on 2023-02-23 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=150)),
                ('price', models.FloatField(default=10.0)),
                ('product_stock', models.IntegerField(default=0)),
                ('pic', models.FileField(default='empty.jpg', upload_to='product_pics')),
                ('selller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
