# Generated by Django 4.1.6 on 2023-02-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='pic',
            field=models.FileField(default='empty.jpg', upload_to='seller_pics'),
        ),
    ]
