# Generated by Django 4.1.7 on 2023-03-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_allorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllOrder',
        ),
    ]
